---
slug: kokebok
filename: kokebok
title: Original Article Title
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2018
uuid: a2724199-a0bf-4140-9a4e-91ea2165e430
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
