---
chapter:
  word: Kapittel
  order: standard     # Use 'reverse' to change 'Chapter 1' to '1 Chapter'
section: Seksjon
table: Tabell
figure: Figur
fig: Fig
aside: Boks
listing: Liste
equation: Ligning
eq: Eq
frontmatter: Forord
contents: Innhold
